// This file is auto-generated by @hey-api/openapi-ts

export type SpeciesForm = {
    id: number;
    name: string;
};

export type ApiErrorBody = {
    /**
     * HTTP status code (e.g., 400, 404, 500)
     */
    code: number;
    /**
     * Short machine-readable error kind (e.g., "bad_request")
     */
    error: string;
    /**
     * Human-readable message for the UI
     */
    message: string;
    /**
     * Optional extra details (validation errors, etc.)
     */
    details?: unknown;
};

export type SpeciesFormsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/species_forms';
};

export type SpeciesFormsErrors = {
    default: ApiErrorBody;
};

export type SpeciesFormsError = SpeciesFormsErrors[keyof SpeciesFormsErrors];

export type SpeciesFormsResponses = {
    200: Array<SpeciesForm>;
};

export type SpeciesFormsResponse = SpeciesFormsResponses[keyof SpeciesFormsResponses];

export type ClientOptions = {
    baseURL: 'http://localhost:8000' | (string & {});
};