INSERT INTO tomes (name, tier) VALUES 
-- Astral
	('Evocation', 1),
	('Warding', 1),
	('Scrying', 2),
	('Summoning', 2),
	('Amplification', 3),
	('Teleportation', 3),
	('Astral Convergence', 4),
	('The Astral Mirror', 4),
	('The Arch Mage', 5),
-- Chaos
	('Pyromancy', 1),
	('The Horde', 1),
	('Mayhem', 2),
	('Revelry', 2),
	('Devastation', 3),
	('Pandemonium', 3),
	('Chaos Channeling', 4),
	('The Demon Gate', 4),
	('The Chaos Lord', 5),
-- Materium 
	('Enchantment', 1),
	('Rock', 1),
	('Artificing', 2),
	('Winds', 2),
	('The Dungeon Depths', 2),
	('Terramancy', 3),
	('Transmutation', 3),
	('The Crucible', 4),
	('The Golden Realm', 4),
	('The Creator', 5),
-- Nature 
	('Beasts', 1),
	('Roots', 1),
	('Fertility', 2),
	('Glades', 2),
	('Cycles', 3),
	('Vigor', 3),
	('Nature''s Wrath', 4),
	('Paradise', 4),
	('The Goddess of Nature', 5),
-- Order 
	('Faith', 1),
	('Zeal', 1),
	('The Beacon', 2),
	('The Inquisition', 2),
	('Virtue', 2),
	('Sanctuary', 3),
	('Subjugation', 3),
	('Exaltation', 4),
	('Supremacy', 4),
	('Archon', 4),
	('The God Emperor', 5),
-- Shadow 
	('Necromancy', 1),
	('Cryomancy', 1),
	('The Doomherald', 2),
	('Souls', 2),
	('The Cold Dark', 3),
	('The Great Transformation', 3),
	('Oblivion', 4),
	('The Reaper', 4),
	('The Eternal Lord', 5),
-- Hybrid
	('Evolution', 1),
	('Alchemy', 1),
	('The Tentacle', 1),
	('Discipline', 1),
	('The Construct', 2),
	('Fey Mists', 2),
	('Shades', 2),
	('Dragons', 3),
	('The Dreadnought', 3),
	('The Cleansing Flame', 3),
	('Corruption', 3),
	('Geomancy', 3),
	('Prophecies', 3),
	('Severing', 4),
	('The Stormborn', 4),
	('Calamity', 4),
	('Prosperity', 4),
	('The Revenant', 4);
